include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT "petrov.maxim.2007@gmail.com")

set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PRINT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application")

set(CPACK_DEBIAN_PACKAGE_NAME "solver")
set(CPACK_RPM_PACKAGE_NAME "solver")

set(CPACK_DMG_VOLUME_NAME "Solver ${PRINT_VERSION}")

set(CPACK_WIX_UPGRADE_GUID "ebae53ed-6f64-41b8-90b1-864dc760d118")
set(CPACK_WIX_PRODUCT_NAME "Solver")
include(CPack)
